### ISSUE TITLE
can we make images fill the screen?

### ISSUE THREAD

**Issue by ismly** [lucasjgordon/Onboarding#1]

**Comment by lucasjgordon** [comment]
Sure, open a PR!

**Comment by ismly** [comment]
Pr?

**Comment by lucasjgordon** [comment]
Pull request

**Comment by ismly** [comment]
Sorry. I dont understand. Maybe you missed my issue. I asked you;
Can we make images, fill the whole screen?
If yes, how can we make it? I want it to fill the whole screen..

**Comment by lucasjgordon** [comment]
You can't currently make the images fill the whole screen. If you would like to do this, please feel free to take a look at the code, add the desired functionality and submit a pull request.

**Comment by ismly** [comment]
I asked you, and you want from me :) 
Ok. I will try..

**Comment by ismly** [comment]
how can we link "skip" button to a viewcontroller with StoryBoard ID?

**Comment by lucasjgordon** [comment]
Currently the UI is generated programmatically from within the view controller, you'd need to edit the controller itself to add a skip button. Were you able to make images fill the whole screen?

**Comment by ismly** [comment]
not the whole screen but, made it bigger. Now, images nearly fill the screen.. I played with numbers only.
